# Use an official OpenJDK image
FROM eclipse-temurin:21-jdk-alpine

# Set working directory inside container
WORKDIR /app

# Copy Maven wrapper and pom.xml first for caching dependencies
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Download dependencies only
RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline

# Copy all source code
COPY src ./src

# Build the jar
RUN ./mvnw clean package -DskipTests

# Expose port
EXPOSE 8080

# Run the jar
CMD ["java", "-jar", "target/Hospital-Scheduler-0.0.1-SNAPSHOT.jar"]